services:
  # Backend Service
  - type: web
    name: ai-visualizer-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://ai-visualizer-frontend.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service
  - type: web
    name: ai-visualizer-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ai-visualizer-backend.onrender.com
